version: "3.9"

services:
  shifts-manager-app:
    container_name: shifts-manager
    working_dir: /app/
    build: .
    ports:
      - "3000:3000"
    volumes:
      - app:/app
      - node_modules:/app/node_modules
    environment:
      - API_URL=`${API_URL}`
  storybook:
    container_name: shifts-manager-storybook
    working_dir: /app/
    build:
      context: .
      dockerfile: Storybook.Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - app:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./